### ISSUE TITLE
Facing issue while deploying RapidAnnotator on apache2 server.

### ISSUE THREAD

**Issue by bruce-wayne99** [RedHenLab/RapidAnnotator-2.0#1]
I have been trying to install RapidAnnotator-2.0 on my system (OS: ubuntu 16.04). I am facing some issue during the installation process.
- I have followed the instructions given on this page: https://github.com/guptavaibhav18197/rapidannotator/blob/master/docs/installation_guide.md
- After configuring the `SQLALCHEMY_DATABASE_URI` I have tried accessing http://localhost:8000/frontpage/ but facing this issue as shown in the screenshot.
![image](https://user-images.githubusercontent.com/25129274/53331815-d01b6c80-3917-11e9-9005-c8a07136063f.png)
- Also while trying to check the tables created in the database I am using for rapidannotator this was the result of **SHOW tables;** command in mysql console. (rapid is the name of the database I am using) 
![image](https://user-images.githubusercontent.com/25129274/53331970-343e3080-3918-11e9-8b58-bfd7d87fdbda.png)
- Any kind of help would be appreciated. Please feel free to ask questions about the installation process I followed.

**Comment by peteruhrig** [comment]
Hi bruce-wayne99,

thanks for letting us know. I installed Rapid Annotator on Ubuntu 16.04 myself but did not run into the problem, so I think we need to try step by step.
I think the most likely problem for the error you are seeing may be the Apache config, because the instructions are not fully clear there.
Can you check whether the paths are correct for your installation in the following lines from `/etc/apache2/sites-enabled/000-default.conf`?
```
<VirtualHost *:8000>

    WSGIScriptAlias / /var/www/rapidannotator/wsgi.py

    <Directory /var/www/rapidannotator>

      Require all granted

    </Directory>

</VirtualHost>
```
If you change them, please restart apache2.

Also, can you post the content of your wsgi.py?

In which path does your Rapid Annotator live?

Best wishes,
Peter

**Comment by bruce-wayne99** [comment]
Hi @peteruhrig , thanks for the quick response. I am able to set up rapidannotator locally by running command `flask run`. However I am still facing is deploying on apache2.
- Here's the wsgi.py and config.py file I have changed also indicating the path where I have cloned the repository.
![image](https://user-images.githubusercontent.com/25129274/53478776-9ecca900-3a9d-11e9-8fa8-8ace0a1ca3b2.png)
- Here's the apache2 config file I am using:
![image](https://user-images.githubusercontent.com/25129274/53478876-d9cedc80-3a9d-11e9-97a6-cb3f142f6931.png)
- I am also attaching the error log of apache2, while I am making requests to localhost:8000 from the browser.
![image](https://user-images.githubusercontent.com/25129274/53478957-071b8a80-3a9e-11e9-8962-448f3496d54b.png)
- As mentioned in the instructions I have uninstalled wsgi for python2 using `sudo apt get remove libapache2-mod-wsgi` and installed wsgi for python3 using `sudo apt-get install python3-pip libapache2-mod-wsgi-py3`
- Please feel free to ask further questions regarding this. Correct me If I am wrong but I think the problem according to the error log of apache2 server might be because we didn't mention the environment to run the wsgi script in. 
![image](https://user-images.githubusercontent.com/25129274/53479378-f1f32b80-3a9e-11e9-89b5-e1796d0cfc8a.png)

**Comment by guptavaibhav18197** [comment]
Hi @bruce-wayne99,

From what you have shared: it seems the link in the wsgi.py should be 

/home/subramanyam/redhen/RapidAnnotator-2.0/

instead of 

/home/subramanyam/redhen/RapidAnnotator-2.0/rapidannotator

Hope that helps.

Best wishes,
Vaibhav

**Comment by peteruhrig** [comment]
Also, localhost:8000 will lead to an error; localhost:8000/frontpage will work.
I think we should actually fix this so that localhost:8000 shows a page with a link to /frontpage.

**Comment by bruce-wayne99** [comment]
@guptavaibhav18197 thanks for the suggestion! I am now able to deploy on apache2 and able to set it up on my localhost.
