### ISSUE TITLE
Setting up Rapid Annotator on apache2 server using virtual environment

### ISSUE THREAD

**Issue by bruce-wayne99** [RedHenLab/RapidAnnotator-2.0#11]
## Description and motivation
- Currently the installation guide (https://github.com/guptavaibhav18197/rapidannotator/blob/master/docs/installation_guide.md) involves installing the python3 dependencies globally.
- Many users might face problems while installing dependencies globally due to version problems.
- We can avoid this problem by suggesting the users to create a virtual environment and installing the dependencies in that environment.
-  We can also change the apache2 configuration to run the application in a virtual environment. 

**I would like to work on this issue**

**Comment by guptavaibhav18197** [comment]
Hi @bruce-wayne99 ,

Yes sure. you can do ahead to add this information.

Thanks
Vaibhav
