### ISSUE TITLE
Adding a new annotation level to an already annotated experiment

### ISSUE THREAD

**Issue by bruce-wayne99** [RedHenLab/RapidAnnotator-2.0#14]
**A brief description of the issue**
- After uploading a dataset of images for annotation, I have initially added 2 annotation levels to the experiment.
- In the below images you can see I have added a` Wikipaintings dataset` experiment consisting of 14 images.
![image](https://user-images.githubusercontent.com/25129274/54633169-a6341080-4aa5-11e9-8838-0a50e3f3a59a.png)
- Intially I have added 2 annotation levels namely `animal` and `body part` as shown in the figure.
![image](https://user-images.githubusercontent.com/25129274/54633422-26f30c80-4aa6-11e9-9481-1cc3a5c5f20f.png)
- After this I have annotated the dataset using these two annotation levels, next I want to annotate the images based on another annotation level say `Image-category`, so I add another annotation level but when I try to annotate the images it's not possible.
- Annotation with present labels
![image](https://user-images.githubusercontent.com/25129274/54633695-b8627e80-4aa6-11e9-9b55-859e0a89ccb9.png)
- New annotation level added.
![image](https://user-images.githubusercontent.com/25129274/54633825-f65fa280-4aa6-11e9-98ae-2c481644d0df.png)
- Not able to annotate the images with this new annotation level.
![image](https://user-images.githubusercontent.com/25129274/54633845-feb7dd80-4aa6-11e9-9741-9e7cd2bb30d8.png)
- In many cases a researcher/annotator might want to re-annotate the images again based on a new category.

**Functionality after solving this issue**
- Annotator should be able to annotate the images of the experiment again based on this new annotation level he added.

*I would like to work on this issue*

**Comment by gulshan-mittal** [comment]
@bruce-wayne99 .This is again feature which can be added and also there are a lot of feature which can be suggested for the Rapid-annotator 2. So its again not a issue.
