### ISSUE TITLE
Adding support for partitioning the data for multiple annotators (feature request)

### ISSUE THREAD

**Issue by bruce-wayne99** [RedHenLab/RapidAnnotator-2.0#15]
**Description of the feature request**
- Once an experiment is added and annotators are assigned to the experiment, the owner of the experiment should be able to partition the images to multiple annotators.
- In this way we can make the annotation process faster and easier.

**Ideas for solving the feature request**
- We can keep an option when the data is added, the owner has the option to assign the data to the annotators based on some range for each annotator.
- This is just an initial idea and it would be great if we could discuss more about the issue in this thread.

*I would like to work on this.*

**Comment by gulshan-mittal** [comment]
@bruce-wayne99 This is a feature request for the project,  not an issue.
