### ISSUE TITLE
No validation of Username and Email

### ISSUE THREAD

**Issue by gulshan-mittal** [RedHenLab/RapidAnnotator-2.0#3]
Hi, @peteruhrig,

There is no validation in username and email in the registration form as lines are commented in the code. 
I have made a pull request to correct it.

**Comment by guptavaibhav18197** [comment]
Hi @gulshan-mittal,

Thanks for pointing it out, but current version is a development version of Rapid Annotator, hence some of the validations are taken off for now.

Thanks,
Vaibhav
