### ISSUE TITLE
Image not loading in annotate experiment page after renaming it

### ISSUE THREAD

**Issue by bruce-wayne99** [RedHenLab/RapidAnnotator-2.0#4]
## Description
- After uploading an image for annotation I am able to see it in the annotating page.
- Next I have renamed the image and logged out.
- Signing in again does not show the image in the annotating page.

## Screenshots of the issue
- Uploaded an barca.jpg under Experiment-3
![image](https://user-images.githubusercontent.com/25129274/53621671-415f6600-3c1d-11e9-972e-d3688bceea02.png)
- Able to see the image in annotation page
![image](https://user-images.githubusercontent.com/25129274/53621714-6d7ae700-3c1d-11e9-88bf-e370545529e4.png)
- Renamed the image to barca1.jpg and logged out.
![image](https://user-images.githubusercontent.com/25129274/53621732-84b9d480-3c1d-11e9-8059-f799d1fecf91.png)
- Logging in again shows no image in the annotation page.
![image](https://user-images.githubusercontent.com/25129274/53621788-ac10a180-3c1d-11e9-9b46-9d14a3abd40e.png)
- We can see the 404 error in the console. The browser was requesting for barca.jpg instead of barca1.jpg.
![image](https://user-images.githubusercontent.com/25129274/53621798-bb8fea80-3c1d-11e9-9fe4-db49f60b16dd.png)

### I would like to work on this issue.

**Comment by guptavaibhav18197** [comment]
Hi @bruce-wayne99,

Thanks for pointing it out. Sure! you can go ahead to fix it.

Best wishes,
Vaibhav
