### ISSUE TITLE
Unexpected behavior when adding or removing annotators at an experiment 

### ISSUE THREAD

**Issue by rrrokhtar** [RedHenLab/RapidAnnotator-2.0#47]
### Description
When adding/removing annotators to an experiment in a some quick way (I did that just for testing the functionality but I found that), it leads to adding same user twice sometimes which is not logical. Is it alright or not very important to look for fixing it?
#### 1 The behavior when using delete and add annotator functionalities.
![Non-logical behavior when using delete and add annotator ](https://user-images.githubusercontent.com/39674365/120403695-ffb24e00-c344-11eb-9ee0-adcbac36a056.gif)
### 2 The delayed delete
![Delayed delete](https://user-images.githubusercontent.com/39674365/120403756-240e2a80-c345-11eb-95bc-54865d5a0c40.gif)

**Comment by peteruhrig** [comment]
This is a problem, and my guess is that it is related to the problem that sometimes the annotators don't get added, in particular in Firefox. I think this definitely needs fixing.
