### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Mec-iS** [RedHenLab/RapidAnnotator-2.0#74]
This repo is the result of a GSOC project but doesn't display a permissive license as required but the GSOC rules.
Please specify the license in a LICENSE file as per other repositories in the same organization.

**Comment by rrrokhtar** [comment]
I see that's already added
that may be closed I guess @peteruhrig

**Comment by peteruhrig** [comment]
Good point, forgot to close this. At Red Hen Lab, we usually use GPLv2.
